<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>245d4528-025f-448f-9e46-08921454fb7a</elementGuidId>
    <imagePath></imagePath>
    <name>link_MyInfo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/aside[1]/nav[1]/div[2]/ul[1]/li[6]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/orangehrm/web/index.php/pim/viewMyDetails') and equals(@text,'My Info')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="My Info"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/orangehrm/web/index.php/pim/viewMyDetails</value>
        <webElementGuid>6d089b04-7c76-4fe2-bbb6-9b40d8c09dcc</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>My Info</value>
        <webElementGuid>6d089b04-7c76-4fe2-bbb6-9b40d8c09dcc</webElementGuid>
    </webElementProperties>
</WebElementEntity>