<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>67f3a50c-adb2-4137-b786-2456954b4dc5</elementGuidId>
    <imagePath></imagePath>
    <name>link_PersonalDetails</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/orangehrm/web/index.php/pim/viewPersonalDetails/empNumber/1') and equals(@text,'Personal Details')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Personal Details"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/orangehrm/web/index.php/pim/viewPersonalDetails/empNumber/1</value>
        <webElementGuid>6d089b04-7c76-4fe2-bbb6-9b40d8c09dcc</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Personal Details</value>
        <webElementGuid>6d089b04-7c76-4fe2-bbb6-9b40d8c09dcc</webElementGuid>
    </webElementProperties>
</WebElementEntity>